#!/bin/sh

if [ "$IFACE" = "{{ upstream_iface }}" ]; then
   iptables -A INPUT -i "$IFACE" -m state --state ESTABLISHED,RELATED -j ACCEPT
   iptables -A INPUT -i "$IFACE" -j DROP
   iptables -P INPUT ACCEPT
fi
