#!/bin/sh

F=/sys/class/net/$IFACE/bonding/slaves
[ -f "$F" ] || exit 0

for slave in `cat "$F"`; do
    ip link set $slave up
    # Disable offloading as it interferes with shaping
    ethtool -K $slave gso off gro off tso off
done
